--Insert into temp presentation 
INSERT INTO temp_presentations (title, speaker, level_name, event_name)
VALUES
('A dive into Data Quality Services', 'Steve Simon', 'Intermediate', 'New York'),
('A Dynamic World Demands Dynamic SQL', 'Jeremiah Peschka', 'Intermediate', 'Kiyv'),
('A Dynamic World Demands Dynamic SQL', 'Jeremiah Peschka', 'Intermediate', 'Kiyv'),
('Absolute Introductory Session on SQL Server 2014 In-Memory Optimized Databases (Hekaton)', 'Kevin Goff', 'Beginner', 'Budapest'),
('AlwaysOn: Improve reliability and reporting performance with one cool tech', 'Chris Seferlis', 'Beginner', 'New York'),
('An introduction to Data Mining', 'Steve Simon', 'Intermediate', 'Kiyv'),
('An Introduction to Database Design', 'Mohammad Yusuf', 'Beginner', 'New York'),
('Autogenerating a process data warehouse', 'Kennie Pontoppidan', 'Advanced', 'New York'),
('Automate your daily checklist with PBM and CMS', 'John Sterrett', 'Intermediate', 'Budapest'),
('Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters', 'Thomas Grohser', 'Intermediate', 'New York'),
('Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters', 'Thomas Grohser', 'Intermediate', 'Kiev'),
('Automating Execution Plan Analysis', 'Joe Chang', 'Advanced', 'Kiev'),
('Automating Execution Plan Analysis', 'Joe Chang', 'Advanced', 'New York'),
('Automating SQL Server using PowerShell', 'Michael Wharton', 'Intermediate', 'New York'),
('Balanced Scorecards using SSRS', 'Sunil Kadimdiwan', 'Intermediate', 'Budapest'),
('Baselines and Performance Monitoring with PAL', 'Mike Walsh', 'Beginner', 'New York'),
('Basic Database Design', 'John Miner', 'Beginner', 'New York'),
('Basic Database Programming', 'John Miner', 'Beginner', 'Kiev'),
('Become a BI Independent Consultant!', 'James Serra', 'Beginner', 'Budapest'),
('Becoming a Top DBA--Learning Automation in SQL Server', 'Joseph D''Antoni', 'Beginner', 'Kiev'),
('Best Practices Document', 'Paresh Motiwala', 'Intermediate', 'Kiev'),
('Best Practices for Efficient SSRS Report Creation', 'Mickey Stuewe', 'Beginner', 'New York'),
('Biggest Loser: Database Edition', 'John Miner', 'Intermediate', 'New York'),
('Building a BI Solution in the Cloud', 'Stacia Misner', 'Intermediate', 'Budapest'),
('Building an Effective Data Warehouse Architecture', 'James Serra', 'Beginner', 'New York'),
('Building an Effective Data Warehouse Architecture with the cloud and MPP', 'James Serra', 'Beginner', 'New York'),
('Bulk load and minimal logged inserts', 'David Peter Hansen', 'Advanced', 'New York'),
('Business Analytics with SQL Server & Power Map:Everything you want to know but were afraid to ask', 'Steve Simon', 'Intermediate', 'New York'),
('Challenges to designing financial warehouses, lessons learnt', 'Steve Simon', 'Intermediate', 'New York'),
('Change Data Capture in SQL Server 2008/2012', 'Kevin Goff', 'Intermediate', 'New York'),
('Changing Your Habits to Improve the Performance of Your T-SQL', 'Mickey Stuewe', 'Beginner', 'Kiev'),
('Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments', 'Allan Hirt and SIOS Technology', 'Beginner', 'Kiev'),
('Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments', 'Allan Hirt', 'Non-Technical', 'Kiev'),
('Coffee Break', 'SQLSatruday 364', 'Non-Technical', 'Budapest'),
('Creating A Performance Health Repository - using MDW', 'Robert Pearl', 'Beginner', 'Kiev'),
('Creating efficient and effective SSRS BI Solutions', 'Steve Simon', 'Intermediate', 'Kiev'),
('Creating efficient and effective SSRS BI Solutions', 'Steve Simon', 'Intermediate', 'New York'),
('Data Partitioning', 'John Flannery', 'Intermediate', 'New York'),
('Data Tier Application Testing with NUnit and Distributed Replay', 'John Flannery', 'Intermediate', 'New York'),
('Database design for mere developers', 'Steve Simon', 'Intermediate', 'Budapest'),
('Database design for mere developers', 'Steve Simon', 'Intermediate', 'New York'),
('Database Design: Solving Problems Before they Start!', 'Edward Pollack', 'Beginner', 'New York'),
('Database Modeling and Design', 'Mohammad Yusuf', 'Intermediate', 'New York'),
('Database Virtualization and Drinking out of the Fire Hose', 'Michael Corey', 'Intermediate', 'New York'),
('DAX and the tabular model', 'Steve Simon', 'Intermediate', 'Kiev'),
('DBA FOR DUMMIES', 'Robert Pearl', 'Beginner', 'Budapest'),
('Dealing With Difficult People', 'Gigi Bell', 'Beginner', 'Kiev'),
('Development Lifecycle with SQL Server Data Tools and DACFx', 'John Flannery', 'Intermediate', 'Kiev'),
('Did You Vote Today? A DBAs Guide to Cluster Quorum', 'Allan Hirt', 'Advanced', 'Kiev'),
('Dimensional Modeling Design Patterns: Beyond Basics', 'Jason Horner', 'Intermediate', 'Kiev'),
('Dimensional Modeling Design Patterns: Beyond Basics', 'Jason Horner', 'Intermediate', 'Budapest'),
('Diving Into Query Execution Plans', 'Edward Pollack', 'Intermediate', 'New York'),
('Dynamic SQL: Writing Efficient Queries on the Fly', 'Edward Pollack', 'Beginner', 'Kiev'),
('Easy Architecture Design for HA and DR', 'Brent Ozar', 'Intermediate', 'New York'),
('Enhancing your career: Building your personal brand', 'James Serra', 'Beginner', 'New York'),
('Establishing a SLA', 'Thomas Grohser', 'Intermediate', 'New York'),
('ETL not ELT! Common mistakes and misconceptions about SSIS', 'Paul Rizza', 'Advanced', 'Budapest'),
('Event Kickoff and Networking', 'SQLSaturday 364', 'Non-Technical', 'New York'),
('Execution Plans: What Can You Do With Them?', 'Grant Fritchey', 'Intermediate', 'New York'),
('Faster, Better Decisions with Self Service Business Analytics', 'Sayed Saeed', 'Intermediate', 'New York'),
('Full Text Indexing Basics', 'John Miner', 'Beginner', 'Budapest'),
('Get your Mining Model Predictions out to all', 'Steve Simon', 'Intermediate', 'New York'),
('Getting a job with Microsoft', 'Paul Rizza', 'Non-Technical', 'New York'),
('Graph Databases for SQL Server Professionals', 'Stéphane Fréchette', 'Intermediate', 'New York'),
('Hacking Exposé - Using SSL to Protect SQL Connections', 'Chris Bell', 'Intermediate', 'New York'),
('Hacking the SSIS 2012 Catalog', 'Andy Leonard', 'Beginner', 'Budapest'),
('Hidden in plain sight: master your tools', 'Varsham Papikian', 'Intermediate', 'New York'),
('Highly Available SQL Server in Windows Azure IaaS', 'David Bermingham', 'Intermediate', 'New York'),
('How to Make a LOT More Money as a Consultant', 'James Serra', 'Beginner', 'New York'),
('How to Think Like the Engine', 'Brent Ozar', 'Intermediate', 'New York'),
('Hybrid Cloud Scenarios with SQL Server 2014', 'George Walters', 'Intermediate', 'Budapest'),
('Hybrid Solutions: The Future of SQL Server Disaster Recovery', 'Allan Hirt', 'Intermediate', 'Budapest'),
('Implementing Data Warehouse Patterns with the Microsoft BI Tools', 'Kevin Goff', 'Intermediate', 'Budapest'),
('Inroduction to Triggers', 'Jack Corbett', 'Beginner', 'Budapest'),
('Integrating Reporting Services with SharePoint', 'Kevin Goff', 'Intermediate', 'New York'),
('Integration Services (SSIS) for the DBA', 'David Peter Hansen', 'Intermediate', 'New York'),
('Introducing Power BI', 'Stacia Misner', 'Beginner', 'New York'),
('Introduction to Database Recovery', 'John Flannery', 'Beginner', 'New York'),
('Introduction to High Availability with SQL Server', 'John Sterrett', 'Beginner', 'New York'),
('Introduction to Powershell for DBA''s', 'John Sterrett', 'Beginner', 'New York'),
('Introduction to SQL Server - Part 1', 'Brandon Leach', 'Beginner', 'New York'),
('Introduction to SQL Server - Part 2', 'Brandon Leach', 'Beginner', 'New York'),
('Is That A Failover Cluster On Your Laptop/Desktop?', 'Allan Hirt', 'Intermediate', 'New York'),
('Leaving the Windows Open', 'Jeremiah Peschka', 'Intermediate', 'New York'),
('Lunch Break', 'SQLSaturday 364', 'Non-Technical', 'New York'),
('Lunchtime Keynote', 'SQLSaturday 364', 'Non-Technical', 'New York'),
('Master Data Services Best Practices', 'Steve Simon', 'Intermediate', 'New York'),
('Master Data Services Disaster Recovery', 'Steve Simon', 'Intermediate', 'New York'),
('Mind your language!! Cursors are a dirty word', 'Steve Simon', 'Intermediate', 'New York'),
('Modern Data Warehousing', 'James Serra', 'Beginner', 'New York'),
('Monitoring Server health via Reporting Services dashboards', 'Steve Simon', 'Intermediate', 'New York'),
('Monitoring SQL Server using Extended Events', 'Hilary Cotter', 'Beginner', 'New York'),
('Multidimensional vs Tabular - May the Best Model Win', 'Stacia Misner', 'Intermediate', 'New York'),
('Murder They Wrote', 'Jason Brimhall', 'Intermediate', 'New York'),
('Never Have to Say "Mayday!!!" Again', 'Mike Walsh', 'Beginner', 'New York'),
('Now you see it! Now you don’t! Conjuring many reports utilizing only one SSRS report.', 'Steve Simon', 'Intermediate', 'New York'),
('Optimal Infrastructure Strategies for Cisco UCS, Nexus and SQL Server', 'Kevin Schenega', 'Non-Technical', 'Budapest'),
('Optimizing Protected Indexes', 'Chris Bell', 'Intermediate', 'Budapest'),
('Partitioning as a design pattern', 'Kennie Pontoppidan', 'Advanced', 'Budapest'),
('Power BI Components in Microsoft''s Self-Service BI Suite', 'Todd Chittenden', 'Beginner', 'New York'),
('Power to the people!!', 'Steve Simon', 'Intermediate', 'Kiyv'),
('PowerShell Basics for SQLServer', 'Michael Wharton', 'Beginner', 'Kiyv'),
('PowerShell for the Reluctant DBA / Developer', 'Jason Horner', 'Beginner', 'Kiyv'),
('Prevent Recovery Amnesia – Forget the Backups', 'Chris Bell', 'Beginner', 'Kiyv'),
('Query Optimization Crash Course', 'Edward Pollack', 'Beginner', 'Kiyv'),
('Raffle', 'SQLSaturday 364', 'Non-Technical', ''),
('Rapid Application Development with Master Data Services', 'Steve Simon', 'Intermediate', 'Kiyv'),
('Recovery and Backup for Beginners', 'Mike Hillwig', 'Beginner', 'Kiyv'),
('Reduce, Reuse, Recycle: Automating Your BI Framework', 'Stacia Misner', 'Intermediate', 'Kiyv'),
('Registrations', 'SQLSaturday 364', 'Non-Technical', ''),
('Replicaton Technologies', 'Hilary Cotter', 'Advanced', 'Kiyv'),
('Reporting Services for Mere DBAs', 'Jason Brimhall', 'Intermediate', 'Kiyv'),
('Scaling with SQL Server Service Broker', 'Hilary Cotter', 'Advanced', 'Kiyv'),
('Scaling with SQL Server Service Broker', 'Hilary Cotter', 'Advanced', 'Kiyv'),
('Self-Service Data Integration with Power Query', 'Stéphane Fréchette', 'Beginner', 'Kiyv'),
('Shortcuts to Building SSIS in .Net', 'Paul Rizza', 'Beginner', 'Kiyv'),
('So You Want To Be A Consultant?', 'Allan Hirt', 'Beginner', 'Kiyv'),
('SQL anti patterns', 'Kennie Pontoppidan', 'Advanced', 'Kiyv'),
('SQL Server 2012/2014 Columnstore index', 'Kevin Goff', 'Intermediate', 'Kiyv'),
('SQL Server 2012/2014 Performance Tuning All Up', 'George Walters', 'Intermediate', 'Kiyv'),
('SQL Server 2014 Data Access Layers', 'Steve Simon', 'Intermediate', 'Kiyv'),
('SQL Server 2014 New Features', 'George Walters', 'Intermediate', 'Kiyv'),
('SQL Server AlwaysOn Availability Groups', 'George Walters', 'Beginner', 'Kiyv'),
('SQL Server and the Cloud', 'David Peter Hansen', 'Beginner', 'Kiyv'),
('SQL Server Compression and what it can do for you', 'Jason Brimhall', 'Advanced', 'Kiyv'),
('SQL Server Reporting Services 2014 on Steroids!!', 'Steve Simon', 'Intermediate', 'Kiyv'),
('SQL Server Reporting Services Best Practices', 'Steve Simon', 'Intermediate', 'Kiyv'),
('SQL Server Reporting Services, attendees choose', 'Kevin Goff', 'Intermediate', 'Kiyv'),
('SQL Server Storage Engine under the hood', 'Thomas Grohser', 'Intermediate', 'Kiyv'),
('SQL Server Storage internals: Looking under the hood.', 'Brandon Leach', 'Advanced', 'Kiyv'),
('SSIS 2014 Data Flow Tuning Tips and Tricks', 'Andy Leonard', 'Beginner', 'Kiyv'),
('Standalone to High-Availability Clusters over Lunch—with Time to Spare', 'Carl Berglund', 'Intermediate', 'Budapest'),
('Stress testing SQL Server', 'Hilary Cotter', 'Advanced', 'Kiyv'),
('Table partitioning for Azure SQL Databases', 'John Miner', 'Beginner', 'Kiyv'),
('Testing', 'Melissa Riley', 'Beginner', 'Kiyv'),
('The future of the data professional', 'Adam Jorgensen', 'Beginner', 'Kiyv'),
('The Quest for the Golden Record:MDM Best Practices', 'Dennis Messina', 'Beginner', 'Budapest'),
('The Quest to Find Bad Data With Data Profiling', 'Richie Rump', 'Intermediate', 'Budapest'),
('The Spy Who Loathed Me - An Intro to SQL Security', 'Chris Bell', 'Beginner', 'Budapest'),
('Tired of the CRUD? Automate it!', 'Jack Corbett', 'Intermediate', 'Budapest'),
('Top 5 Ways to Improve Your triggers', 'Aaron Bertrand', 'Intermediate', 'Budapest'),
('Tricks that have saved my bacon', 'Greg Moore', 'Beginner', 'Budapest'),
('T-SQL : Bad Habits & Best Practices', 'Aaron Bertrand', 'Beginner', 'Budapest'),
('T-SQL for Application Developers - Attendees chose', 'Kevin Goff', 'Intermediate', 'Budapest'),
('Tune Queries By Fixing Bad Parameter Sniffing', 'Grant Fritchey', 'Intermediate', 'Budapest'),
('Using Extended Events in SQL Server', 'Jason Brimhall', 'Advanced', 'Budapest'),
('Watch Brent Tune Queries', 'Brent Ozar', 'Intermediate', 'Budapest'),
('What every SQL Server DBA needs to know about Windows Server 10 Technical Preview', 'David Bermingham', 'Intermediate', 'Budapest'),
('What exactly is big data and why should I care?', 'James Serra', 'Beginner', 'Budapest'),
('What is it like to work for Microsoft?', 'James Serra', 'Beginner', 'Budapest'),
('What’s new in SQL Server Integration Services 2012', 'Kevin Goff', 'Intermediate', 'Budapest'),
('Why do we shun using tools for DBA job?', 'Paresh Motiwala', 'Intermediate', 'Budapest'),
('Why OLAP? Building SSAS cubes and benefits of OLAP', 'Kevin Goff', 'Intermediate', 'Budapest'),
('You''re Doing It Wrong!!', 'Mike Walsh', 'Intermediate', 'Budapest');
